### ISSUE TITLE
Clerical error on data segmentation

### ISSUE THREAD

**Issue by Chi20** [xiangzhang1015/Deep-Learning-for-BCI#3]
![1](https://user-images.githubusercontent.com/55939465/153735615-3792e20a-87af-410d-9757-987c449df52e.png)
In [tutorial](https://github.com/xiangzhang1015/Deep-Learning-for-BCI/tree/master/tutorial)/2-Preprocessing.ipynb 
Data Segmentation part,**0.1** is mistakenly written as **0.6** in the equation

**Comment by xiangzhang1015** [comment]
Yes, indeed. Thank you for pointing it out.
