### ISSUE TITLE
the problem of transpose in Uniform normalization (L1)

### ISSUE THREAD

**Issue by Chi20** [xiangzhang1015/Deep-Learning-for-BCI#4]
![image](https://user-images.githubusercontent.com/55939465/153744207-7744457e-c9eb-40b6-bf0a-cb44bd4cab3b.png)
In part 2-Preprocessing.ipynb, it seems that no need to transpose the data (may caused by version inprovement)
fyi:my sklearn version is '0.24.1'
![image](https://user-images.githubusercontent.com/55939465/153744413-47147f69-8611-42f2-baad-b631c9183808.png)

**Comment by xiangzhang1015** [comment]
Thank you. I was using a prior version which can only do normalization across the rows.
